FROM node:14.18.2-alpine3.13
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ENV PORT=5000
ENV MONGODB_URI=mongodb+srv://Farzan:Mongodb@123@cluster0.7afeh.mongodb.net/NoorNFT_test?retryWrites=true&w=majority


EXPOSE 5000
CMD ["npm", "start"]
